djvu-change-info: add Python version check.
Before:

    $ python2.5 djvu-change-info
    djvu-change-info:54: Warning: 'with' will become a reserved keyword in Python 2.6
      File "djvu-change-info", line 54
        with open(file, 'r+b') as file:
                ^
    SyntaxError: invalid syntax

After:

    $ python2.5 djvu-change-info
      File "djvu-change-info", line 28
        b''  # Python >= 2.6 is required
          ^
    SyntaxError: invalid syntax